# Sample requests
# Use in Visual Studio Code with REST Client extension
# Some functionality is not supported in Visual Studio
@host =  http://localhost:7286/api

### Get all articles
GET {{host}}/articles
Content-Type: application/json

### Create a new article with file upload
POST {{host}}/articles
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="category"

Shopping
--boundary
Content-Disposition: form-data; name="file"; filename="shopping-list.md"
Content-Type: text/markdown

This is a sample markdown file
--boundary--

### Delete an article
DELETE {{host}}/articles
Content-Type: application/json

{
  "id": "0efa1d43-65ef-4ee6-9929-15634ef9870e",
  "category": "Cooking",
}

### Get all assistants
GET {{host}}/assistants
Content-Type: application/json

### Create a new assistant
POST {{host}}/assistants
Content-Type: application/json

{
  "category": "Cooking",
  "prompt": "You play the role of assistant. Answer questions as best as you can."
}

### Get assistant chat
@message=Can you group the shopping list items by category?
GET {{host}}/assistants/c7a65ed7-21e8-4a2d-82cc-c25c275be331/chat?message={{message}}
Content-Type: application/json

### Delete an assistant
DELETE {{host}}/assistants
Content-Type: application/json

{
  "id": "8742841f-046b-40fd-89ea-32503a36c98c",
  "category": "Cooking",
  "prompt": "You play the role of assistant. Answer questions as best as you can."
}